version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - CORS_ORIGIN=http://localhost:8080,https://la-economica.netlify.app
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - la-economica-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - la-economica-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  # Nginx Proxy (opcional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - la-economica-network
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

networks:
  la-economica-network:
    driver: bridge

volumes:
  backend_node_modules:
  frontend_node_modules:
