[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"

[services.variables]
NODE_ENV = "production"
PORT = "5000"
