[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run start:backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"

[services.variables]
NODE_ENV = "production"
PORT = "5000"

[[services]]
name = "frontend"
source = "."
buildCommand = "npm run build"
startCommand = "npm run preview"

[services.variables]
NODE_ENV = "production"
VITE_API_URL = "${{backend.RAILWAY_PUBLIC_DOMAIN}}"
